language: php

php:
    - 5.3
    - 5.4

before_script:
    - git config --global user.email test@test.com
    - git config --global user.name "Test User"
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
