language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: '7.1'
      env: COVERAGE='true'
    - php: '7.1'
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true

install:
  - set -eo pipefail
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist $COMPOSER_FLAGS

before_script:
    - git config --global user.email test@test.com
    - git config --global user.name "Test User"

script:
  - |
    if [ "$COVERAGE" == "true" ]; then
        make tc
    else
        make test
    fi

notifications:
    email: false


